version: '2'

services:
    php:
        build: .
        volumes:
            - .:/app
        links:
            - kafka
    
    zookeeper:
        image: bitnami/zookeeper:3.5.5
        expose:
            - 2181
        environment:
            - ZOO_ENABLE_AUTH=yes
            - ZOO_SERVER_USERS=kafka
            - ZOO_SERVER_PASSWORDS=kafka_password
        volumes:
            - ~/.backup/zookeeper/kafka-php:/bitnami/zookeeper
    
    kafka:
        image: bitnami/kafka:2.3.0
        expose:
            - 9092
        links:
            - zookeeper
        environment:
            - ALLOW_PLAINTEXT_LISTENER=true
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_ZOOKEEPER_USER=kafka
            - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
            # - KAFKA_CFG_LISTENERS=SASL_SSL://:9092
            # - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
        volumes:
            - ~/.backup/kafka/kafka-php:/bitnami/kafka
